### ISSUE TITLE
Error modifying .config/lxsession/LXDE-pi/autostart

### ISSUE THREAD

**Issue by nmveld1** [gohai/processing-uploadtopi#15]
Hi!

I have a problem regarding the autostart file on my Pi. I did a clean install for a new project where I have a Processing patch sending a live feed to multiple led strips using the FadeCandy. I would like to boot my Pi into this project but it doesn't seem to be able to find the autostart file. 

Does anyone know how to fix this? Thanks!

nmveld

**Comment by gohai** [comment]
Hello nmveld,

The Upload to Pi tool is likely not compatible with your version of the
operating system. I am no longer working on maintaining this software,
sorry.
