### ISSUE TITLE
unknow host

### ISSUE THREAD

**Issue by matheplica** [gohai/processing-uploadtopi#4]
Hi, I'm trying to upload to my pi, on a miniban distribution,
but I have always unknow host errors.
My laptop recognize the pi : 
avahi-resolve -a 192.168.0.101 give me : minibian.local
I put it in preferences.txt.
Where is the bug ?

**Comment by gohai** [comment]
What OS do you have Processing & the UploadToPi tool installed?

What happens when you `ping 192.168.0.101` from this computer? What happens when you `ping minibian.local`?

On the same computer, close all instances of Processing. Then open `preferences.txt`. What is `gohai.uploadtopi.hostname` set to?

**Comment by matheplica** [comment]
OK, I'm working on Linux ubuntuStudio 16.10
The ping with numbers works well but not with minibian.local.
and I set gohai.uploadtopi.hostname=minibian.local

**Comment by gohai** [comment]
@matthieu21 If you can't ping `minibian.local`, them the problem is not with the tool, but with your operating system's capability to resolve those mDNS/DNS-SD addresses.

Set `gohai.uploadtopi.hostname` to `192.168.0.101` and you should be fine.

**Comment by matheplica** [comment]
It's better but now I have this error : 
Could not delete /home/mathieu21/Documents/processingSketch/OpArt/cirque/application.linux64
Error modifying .config/lxsession/LXDE-pi/autostart
./cirque/cirque: 5: ./cirque/cirque: java: not found

**Comment by gohai** [comment]
@matthieu21 This is because you don't have Java installed - which is installed by the default on Raspbian, but not on your "minibian" it seems. You'd be better off staying with regular Rasbian to be honest...

**Comment by matheplica** [comment]
I installed oracle java8-jdk and it's work now. 
With a shortcup with key (shif -+ P) this tool will be perfect.
Thank you for your job. I'm very happy
I have just these two errors : 

> Could not delete /home/mathieu21/Documents/processingSketch/OpArt/cirque/application.linux64
Error modifying .config/lxsession/LXDE-pi/autostart
